name: Playground Action

on: [push, workflow_dispatch]

env:
    SUPER_SECRET: ${{ secrets.NOT_REALLY_SECRET }}
    enhanced_logging: true

jobs:
  one:
    runs-on: windows-2019
    steps:
    - name: Test logic
      run: |

        echo "github event = " + ${{ github.event }}
        echo "enhanced logging = $Env:enhanced_logging"

        if ($Env:enhanced_logging -eq $True) {
          echo "enhanced logging on"
        } else {
          echo "enhanced logging off"
        }
      shell: powershell
