name: Playground Action

on: [push, workflow_dispatch]

env:
    SUPER_SECRET: ${{ secrets.NOT_REALLY_SECRET }}

jobs:
  foo:
    name: foo
    runs-on: windows-2019
    strategy:
        matrix:
            # namespace: [ AgentFeatures, Api, AspNetCore, BasicInstrumentation, CatInbound, CatOutbound, CSP,
            #   CustomAttributes, CustomInstrumentation, DistributedTracing, DistributedTracing.W3CInstrumentationTests, 
            #   HttpClientInstrumentation.NetCore, HttpClientInstrumentation.NetFramework, Logging, Owin, ReJit.NetCore, 
            #   ReJit.NetFramework, RemoteServiceFixtures, RestSharp, WCF.Client, WCF.Client.IIS, WCF.Client.IIS.ASPDisabled, 
            #   WCF.Client.IIS.ASPEnabled, WCF.Client.Self, WCF, WCF.Service, WCF.Service.IIS, WCF.Service.IIS.ASPDisabled, 
            #   WCF.Service.IIS.ASPEnabled, WCF.Service.Self ] 
            namespace: [ AgentFeatures, Api ]
    steps:
      - name: Test Default Branch
        id: default-branch
        env:
            WORKSPACE: ${{ matrix.namespace }}
        run: |
            echo "namespace: NewRelic.Agent.IntegrationTests.${WORKSPACE}"
        shell: bash

      - name: Hexdump secrets
        run: |
            "$Env:SUPER_SECRET" | Format-Hex
      
      - name: Test secrets BOM 
        run: |
            mkdir test_project
            cd test_project
            dotnet new console
            dotnet user-secrets init
            "$Env:SUPER_SECRET" | %{$_ -replace "\xEF\xBB\xBF",''} | dotnet user-secrets set
        shell: powershell